version: '3.9'

services:
  backend:
    image: ghcr.io/fecamp-cu/fe-2021-backend:master
    container_name: fecamp-backend
    restart: always
    env_file:
      - .env.production
    networks:
      - fecamp
      - traefik-net
    ports:
      - ${PORT}:8000
    depends_on:
      - db
    links:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.fe.in.th`)'
      - 'traefik.http.routers.backend.entrypoints=web'
      - 'traefik.docker.network=traefik-net'
  db:
    image: postgres:14.1
    container_name: fecamp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/postgres/prod:/var/lib/postgresql/data
    networks:
      - fecamp
    ports:
      - ${DATABASE_PORT}:5432

  reverse-proxy:
    image: traefik:2.6.1
    container_name: reverse-proxy
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  fecamp:
    name: fecamp
  traefik-net:
    name: traefik-net
