version: '3.9'

services:
  backend:
    image: ghcr.io/fecamp-cu/fe-2021-backend:master
    container_name: fecamp-backend
    restart: always
    env_file:
      - .env.production
    networks:
      - fecamp
      - traefik-net
    depends_on:
      - db
    links:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.fe.in.th`)'
      - 'traefik.http.services.backend.loadbalancer.server.port=8000'
      - 'traefik.http.routers.backend.entrypoints=web'
      - 'traefik.docker.network=traefik-net'
  db:
    image: postgres:14.1
    container_name: fecamp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - fecamp

  portainer:
    image: portainer/portainer-ce:2.11.1
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_portainer.rule=Host(`portainer.fe.in.th`)"
      - "traefik.http.routers.frontend_portainer.entrypoints=web"
      - "traefik.http.services.frontend_portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend_portainer.service=frontend_portainer"
      - "traefik.http.routers.frontend_portainer.tls.certresolver=leresolver"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.fe.in.th`)"
      - "traefik.http.routers.edge.entrypoints=web"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"

  reverse-proxy:
    image: traefik:2.6.1
    container_name: reverse-proxy
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  fecamp:
    name: fecamp
  traefik-net:
    name: traefik-net
volumes:
  portainer_data:
  database:


